# Generated by Django 5.2.17 on 2026-09-14 18:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion_corta', models.CharField(max_length=255)),
                ('descripcion_larga', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('precio_neto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock_actual', models.PositiveIntegerField()),
                ('stock_minimo', models.PositiveIntegerField()),
                ('stock_bajo', models.PositiveIntegerField()),
                ('stock_alto', models.PositiveIntegerField()),
            ],
        ),
    ]
