# Generated by Django 5.2.17 on 2026-09-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('rubro', models.CharField(max_length=150)),
                ('razon_social', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('contacto_nombre', models.CharField(max_length=150)),
                ('contacto_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
